language: R
sudo: false
cache: packages
notifications:
  email: never
  slack:
    on_failure: always
    on_success: change
    secure: qy3TjC8QgNjO+PhTHII+Atfe5VDCOCC1kjy+nh3pgTE2x0VAphzugJePi3pt7/NtwCMSr58c7H+6ueSamjs5nmRGcSvUcWNFhlx5bWuSZH1l9DJVm/s/LuctOMXCpLUzeMD5CZUPSLvx1FEOAv94+BtYoOWGrjB82kTWvPZIne+EbgCPhLqDQSNI21dQ3og1dj1IZUviIYcNSY0/vFKD2CSEYpO8f5JYXvRdPQ425sI1ijl2B+fmuH8dfz6b3STmPAmDaSI+pVbtAmvo6aIKbEygQdENUHSF0CJTCYQIDwLoF8X8mOltieHMO5iFjrQCRfL9Asd8s5e2a3Jh8cfGWZRqPvcl1bip35NLpiA+fk51tfXtISVag5Yh1SWg+opmh5icGhZH1BweGMeXwIEII1T0jusO35NSau8WpMIBZzwa5LF2GRJsQCUiJt8THQT2iJTq686qyqCRI3QxvkpGE490duZMCWoqNxGaCTafKkbeEFSBnqxnU1lGGRQ98KyKkZJMUxFdZyGzG1D3Kk6skM0BM6FY/+SliHmhzf5rTGBqKL+NxWtTQ6VHZjCgkOWEgSKoxf4g9ju9irJYtgWi1c6YCS7XnuS1CQFMPKZQtV5Jh0AKzfqb5crKQf211Pb3ifdNJGg3kKSHbX7+muznxGgOWiF1vtjbSh+j3mU7buc=
