#!/usr/bin/env Rscript

'aggregate

Usage:
  aggregate.R <sqlite_file> -o <file> [-m <operation>] [-s <strata>] [-v <variables>]

Options:
  -h --help                                Show this screen.
  -o <file> --output=<file>                Output file for storing aggregated profiles.
  -m <operation> --operation=<operation>   Method for aggregation. [default: mean].
  -s <strata> --strata=<strata>            Comma-separated list of grouping variables for aggregation. [default: Image_Metadata_Plate,Image_Metadata_Well]
  -v <variables> --variables=<variables>   Comma-separated list of observation variables to be aggregated. [default: all]

Arguments:
  sqlite_file                              Filename of SQLite data base storing morphological profiling data ' -> doc

#docopt::docopt(doc, args = "test.sqlite -o test.csv")

opts <- docopt::docopt(doc)

cytotools::aggregate(sqlite_file = opts[["sqlite_file"]],
                     output_file = opts[["output"]],
                     operation = opts[["operation"]],
                     variables = stringr::str_split(opts[["variables"]], ",")[[1]],
                     strata = stringr::str_split(opts[["strata"]], ",")[[1]])
