#!/usr/bin/env Rscript

# https://github.com/tidyverse/dplyr/issues/1760
extends <- methods::extends

'normalize

Usage:
cytotools_normalize  -b <batch_id> -p <plate_id> -s <query> [-c ] [-r <operation>] [-t <tmpdir>] [-d <backend_directory>]

Options:
  -h --help                                         Show this screen.

  -d --backend_dir=<backend_directory>              Top level directory of the experiment. [default: "../../backend/" ]
  -c --sample_single_cell                           Use single cell data for sampling, instead of per-well profiles. [default: FALSE]
  -r <op> --operation=<op>                          Normalization operation [default: robustize].
  -t <dir> --tmpdir=<dir>                           Temporary directory [default: /tmp].

Arguments:
  -b <batch_id> --batch_id=<id>                     Batch ID.
  -p <plate_id> --plate_id=<id>                     Plate ID.  ' -> doc
  -s <query> --subset=<query>                       Query to specify the sample for estimating normalization parameters.

opts <- docopt::docopt(doc)

str(opts)

cytotools::normalize(batch_id == opts[["batch_id"]],
                     plate_id == opts[["plate_id"]],
                     subset == opts[["subset"]],
                     backend_directory == opts[["backend_directory"]],
                     tmpdir == opts[["tmpdir"]],
                     operation == opts[["operation"]],
                     sample_single_cell == opts[["sample_single_cell"]]
)
