#!/usr/bin/env Rscript

# https://github.com/tidyverse/dplyr/issues/1760
extends <- methods::extends

'aggregate

Usage:
  cytotools_aggregate <sqlite_file> -o <file>  [-c <compartments>] [-m <operation>] [-s <strata>] [-v <variables>] [-f <variables>] [-u]

Options:
  -h --help                             Show this screen.
  -o <file> --output=<file>             Output file for storing aggregated profiles.
  -c <str> --compartments=<str>         Comma-separated list of cellular compartments. [default: cells,cytoplasm,nuclei].
  -m <str> --operation=<str>            Method for aggregation. [default: mean].
  -s <str> --strata=<str>               Comma-separated list of grouping variables for aggregation. [default: Metadata_Plate,Metadata_Well]
  -f <str> --image_variables=<str>      Comma-separated list of variables to include from image tables. By default, none are included.
  -t <str> --image_table=<str>          Name of image table. [default: image]
  -v <str> --variables=<str>            Comma-separated list of observation variables to be aggregated. [default: all]
  -u --multivariate                     Aggregation function is multivariate.

Arguments:
  sqlite_file                           Filename of SQLite database storing morphological profiling data.' -> doc

opts <- docopt::docopt(doc)

cytotools::aggregate(sqlite_file = opts[["sqlite_file"]],
                     output_file = opts[["output"]],
                     compartments = stringr::str_split(opts[["compartments"]], ",")[[1]],
                     operation = opts[["operation"]],
                     variables = stringr::str_split(opts[["variables"]], ",")[[1]],
                     strata = stringr::str_split(opts[["strata"]], ",")[[1]],
                     image_variables = ifelse(is.null(opts[["image_variables"]]), NULL, stringr::str_split(opts[["image_variables"]], ",")[[1]]),
                     image_table = opts[["image_table"]],
                     univariate = !opts[["multivariate"]])
