#!/usr/bin/env Rscript

# https://github.com/tidyverse/dplyr/issues/1760
extends <- methods::extends

'aggregate

Usage:
  cytotools_aggregate <sqlite_file> -o <file>  [-c <compartments>] [-m <operation>] [-s <strata>] [-v <variables>] [-u]

Options:
  -h --help                                         Show this screen.
  -o <file> --output=<file>                         Output file for storing aggregated profiles.
  -c <compartments> --compartments=<compartments>   Comma-separated list of cellular compartments. [default: cells,cytoplasm,nuclei].
  -m <operation> --operation=<operation>            Method for aggregation. [default: mean].
  -s <strata> --strata=<strata>                     Comma-separated list of grouping variables for aggregation. [default: Metadata_Plate,Metadata_Well]
  -v <variables> --variables=<variables>            Comma-separated list of observation variables to be aggregated. [default: all]
  -u --multivariate                                 Aggregation function is multivariate.

Arguments:
  sqlite_file                                       Filename of SQLite database storing morphological profiling data ' -> doc

opts <- docopt::docopt(doc)

cytotools::aggregate(sqlite_file = opts[["sqlite_file"]],
                     output_file = opts[["output"]],
                     compartments = stringr::str_split(opts[["compartments"]], ",")[[1]],
                     operation = opts[["operation"]],
                     variables = stringr::str_split(opts[["variables"]], ",")[[1]],
                     strata = stringr::str_split(opts[["strata"]], ",")[[1]],
                     univariate = !opts[["multivariate"]])
