#!/usr/bin/env Rscript

# https://github.com/tidyverse/dplyr/issues/1760
extends <- methods::extends

'normalize

Usage:
cytotools_normalize -b <batch_id> -p <plate_id> -s <query> [-c <compartments>] [-d <backend_directory>] [-m <operation>] [-r <strata>]

Options:
  -h --help                                         Show this screen.
  -b <batch_id> --batch_id=<id>                     Batch ID.
  -p <plate_id> --plate_id=<id>                     Plate ID.
  -s <query> --subset=<query>                       Query to specify the sample for estimating normalization parameters.
  -c <compartments> --compartments=<compartments>   Comma-separated list of cellular compartments. [default: cells,cytoplasm,nuclei].
  -d --backend_dir=<backend_directory>              Top level directory of the experiment. [default: "../../backend/" ]
  -m <operation> --operation=<operation>            Method for normalization [default: robustize].
  -r <strata> --strata=<strata>                     Comma-separated list of grouping variables for normalization. [default: Metadata_Plate]' -> doc

#docopt::docopt(doc, args = "test.sqlite -o test.csv")

opts <- docopt::docopt(doc)

str(opts)

cytotools::normalize(batch_id = opts[["batch_id"]],
                     plate_id = opts[["plate_id"]],
                     subset = opts[["subset"]],
                     backend_directory = opts[["backend_directory"]],
                     compartments = stringr::str_split(opts[["compartments"]], ",")[[1]],
                     operation = opts[["operation"]],
                     strata = stringr::str_split(opts[["strata"]], ",")[[1]])
