#!/usr/bin/env Rscript

"cytotools_hello

Usage:
cytotools_hello <msgtext>

Options:
-h --help Show this screen." -> doc

suppressWarnings(suppressMessages(library(docopt)))

suppressWarnings(suppressMessages(library(cytotools)))

opts <- docopt(doc)

msgtext <- opts[["msgtext"]]

cytotools::hello(msgtext)
