#!/usr/bin/env Rscript

# https://github.com/tidyverse/dplyr/issues/1760
extends <- methods::extends

'annotate

Usage:
  annotate.R -b <id> -p <id> [-c <str> -d -j <file> -m <str> -o <file> -w <file>]

Options:
  -b <id> --batch_id=<id>                 Batch ID.
  -p <id> --plate_id=<id>                 Plate ID.
  -c <str> --cell_id=<str>                Cell ID [default: unknown]
  -d --format_broad_cmap                  Add columns to make compatible with Broad CMap naming conventions.
  -j <file> --external_metadata=<file>    Optional external metadata to join with, as a CSV file.
  -m <str> --perturbation_mode=<str>      Mode of perturbation - chemical or genetic [default: chemical]
  -o <file> --output=<file>               Output file for storing annotated profiles [default: workspace_directory/backend/batch_id/plate_id/plate_id_augmented.csv]
  -w <file> --workspace_directory         Root directory containing backend and metadata subdirectories [default: .]' -> doc

opts <- docopt::docopt(doc)

cytotools::annotate(opts[["batch_id"]], opts[["plate_id"]],
                    cell_id = opts[["cell_id"]],
                    external_metadata = opts[["external_metadata"]],
                    format_broad_cmap = opts[["format_broad_cmap"]],
                    output = opts[["output"]],
                    perturbation_mode = opts[["perturbation_mode"]],
                    workspace_dir = opts[["workspace_directory"]])
